paths:
  uploads: uploads
  dam_uploads: ''
  static: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: _posts
    output: true
    icon: notes
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: ''
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
collections_config_override: true
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_select_data: {}
_structures: {}
_editables:
  text:
    bold: true
    copyformatting: true
    italic: true
    link: true
    paths:
    redo: true
    removeformat: true
    strike: true
    subscript:
    superscript:
    underline: true
    undo: true
  image:
    correct_orientation: true
    expandable: true
    height: 100
    image_size_attributes: true
    mime_type:
    paths:
    resize_style: cover
    width: 100
  link:
    paths:
      uploads:
      dam_uploads:
      dam_static:
data_config: {}
editor:
  default_path:
timezone: Etc/UTC
