site_logo_url: /assets/images/logo.svg
site_name: Louisiana Tactical	
email: Louisianatactical@yahoo.com
phone: 337-224-1729
address: 914 Cypress St, Sulphur, LA 70663
ga_id: 
head_code: ''
footer_code: ''
