site_logo_url: /assets/images/logo.svg
site_name: LA Tactical Supply
email: Louisianatactical@yahoo.com
phone: 337-224-1729
address: 907 Country Ridge Rd, Opelousas, LA 70570
ga_id:
head_code: ''
footer_code: ''
social:
  - name: Facebook
    link: https://www.facebook.com/profile.php?id=100069392407833
    icon: facebook
